import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono"
import "./globals.css";
import { ConvexClerkProvider } from "../providers/ConvexClerkProvider";
import { Toaster } from "../components/ui/sonner"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en">
        <body className={`${GeistMono.className} antialiased h-screen bg-gradient-to-br from-zinc-900 to-black`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
